2020-12-16 09:52:26,982 - D:\ZYCami_00\Public\Caplictily.py[line:44] - ERROR: 错误：HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F529482EC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2020-12-16 09:52:27,004 - D:\ZYCami_00\PO\Base_page.py[line:30] - ERROR: ('xpath', '//android.widget.FrameLayout[@content-desc="Me"]/android.widget.ImageView')元素可见失效，错误：'NoneType' object has no attribute 'find_element'
2020-12-16 10:11:18,721 - D:\ZYCami_00\PO\Base_page.py[line:30] - ERROR: ('xpath', '//android.widget.FrameLayout[@content-desc="Me"]/android.widget.ImageView')元素可见失效，错误：Message: 

